"""add cascade delete to comment client_id

Revision ID: a123403d64ce
Revises: cbf57dd16065
Create Date: 2025-05-17 02:10:30.327227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a123403d64ce'
down_revision: Union[str, None] = 'cbf57dd16065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('comments_client_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_client_id_fkey', 'comments', 'clients', ['client_id'], ['id'])
    op.alter_column('comments', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
